DOBOT_IP = "192.168.5.1"
SPEED_RATIO = 30

LASER_DLL_PATH = r"Laser\REMOTECONTROL.dll" # need to update
LASER_FIRE_MODE = "Continuous"
LASER_SYNC_MODE = "INTERNAL"
LASER_SYNC_DELAY = "-80"
LASER_WAVELENGTH_NM = 850

TRIGGER_DO_INDEX = 1
TRIGGER_PULSE_SECONDS = 0.001

STEP_DISTANCE_MM = 0.5
TOTAL_DISTANCE_MM = 150
LOOP_REPEAT_COUNT = 1
STEP_WAIT_SECONDS = 0.150
